CREATE TABLE [dbo].[tbl_RACES]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [RACE_NAME] NVARCHAR(50) NULL, 
    [RACE_DESCRIPTION] NVARCHAR(50) NULL, 
    [RACE_FEATURES] NVARCHAR(MAX) NULL, 
    [RACE_LIFESPAN] INT NULL, 
    [RACE_ALIGNMENT] INT NULL
)
