CREATE TABLE [dbo].[tbl_ITEMS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ITEM_NAME] NVARCHAR(50) NULL, 
    [ITEM_DESCRIPTION] NVARCHAR(50) NULL, 
    [ITEM_RARITY] INT NULL, 
    [ITEM_STAT_AFFINITY] NVARCHAR(MAX) NULL, 
    [ITEM_STAT_AFFINITY_VALUE] CHAR(2) NULL
)
