CREATE TABLE [dbo].[tbl_SPELLS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [SPELL_NAME] NVARCHAR(50) NULL, 
    [SPELL_DESCRIPTION] NVARCHAR(MAX) NULL, 
    [SPELL_LEVEL] INT NULL, 
    [SPELL_CLASSES] NVARCHAR(MAX) NULL
)
